server:
  port: 8081

fc:
  auth:
    url: http://localhost:8090
    client:
      id: customer-service
      secret: customer-secret
  config:
    database:
      schema: fc_customer
    file:
      upload-dir: uploads
    accounts:
      url: http://localhost:8082

spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_core?currentSchema=${fc.config.database.schema}
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        default_schema: ${fc.config.database.schema}
    hibernate:
      ddl-auto: validate
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active: oauth,web
  security:
    oauth2:
      client:
        registration:
          account-service:
            client_id: ${fc.auth.client.id}
            client_secret: ${fc.auth.client.secret}
            authorization-grant-type: client_credentials
            scopes: service.read,service.write,internal.api
            provider: auth-server
        provider:
          auth-server:
            token-uri: ${fc.auth.url}/oauth2/token
    user:
      name: financecore
      password: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka